obstacle_range: 6.5
raytrace_range: 8.5
footprint: [[0.15, 0.25], [0.15, -0.25], [-0.15, 0.25], [-0.15, -0.25]]

inflation_radius: 0.2

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: czujnik_odleglosci, data_type: LaserScan, topic: scan, marking: true, clearing: true}

